#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(np.__version__)

1.26.4


#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
vector = np.zeros(10)
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [4]:
list = np.zeros(10)
print(list.nbytes)

80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)


In [ ]:
help(np.add)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
vector = np.zeros(10)
vector[4]=1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
vector =np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
vector =np.arange(10,50)
print(np.flip(vector))

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [11]:
matrix = np.arange(9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [12]:
vector = np.array([1,2,0,0,4,0])
index_of_nonZero= np.nonzero(vector)[0]
print(index_of_nonZero)

[0 1 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [14]:
matrix = np.eye(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [15]:
matrix = np.random.rand(3, 3, 3)
print(matrix)

[[[0.54137032 0.49171503 0.88389887]
  [0.85335196 0.95436903 0.68550034]
  [0.4892862  0.44869711 0.79324676]]

 [[0.65547324 0.86954844 0.33837689]
  [0.39363757 0.84667064 0.01107116]
  [0.19352264 0.24169089 0.18273265]]

 [[0.84630669 0.37876971 0.27850565]
  [0.89709225 0.78200032 0.81523628]
  [0.11389327 0.6125415  0.31073996]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [16]:
matrix = np.random.rand(10,10)
print(matrix)
print(np.max(matrix))
print(np.min(matrix))

[[0.72242766 0.1676865  0.93595237 0.70247279 0.55975247 0.93406821
  0.52687346 0.01308614 0.08678924 0.16374723]
 [0.48885311 0.08964168 0.9749668  0.04816773 0.71837984 0.19700902
  0.38555096 0.59774513 0.58985989 0.63339282]
 [0.71738518 0.10186546 0.96864216 0.86123738 0.75967925 0.88824288
  0.57437641 0.87702577 0.75077656 0.75044188]
 [0.23734776 0.59765147 0.47102398 0.78296413 0.14247819 0.47274399
  0.52346276 0.72850475 0.26016906 0.43210223]
 [0.74754753 0.85042573 0.48815504 0.69667138 0.55727467 0.12753328
  0.48994119 0.55776631 0.60744034 0.79448211]
 [0.92584018 0.24735591 0.00778317 0.90368052 0.79859976 0.80622684
  0.15309821 0.31474342 0.89539009 0.32771052]
 [0.05703797 0.00846884 0.85534851 0.92154615 0.61150636 0.93498025
  0.34949517 0.0742571  0.91482097 0.43583812]
 [0.95966476 0.04004756 0.3296619  0.20486012 0.15154937 0.47475856
  0.18229054 0.69847777 0.45875366 0.34326989]
 [0.21252905 0.52066499 0.9004432  0.19799965 0.88778978 0.82334882
  0.74419634

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [28]:
vector = np.random.rand(30)
mean = np.mean(vector)
print(vector)
print(mean)

[0.59843631 0.68049708 0.59138957 0.42588917 0.62020701 0.42797697
 0.34069682 0.61065195 0.86151819 0.67797257 0.46037809 0.09753708
 0.92565382 0.04800095 0.64466143 0.85961311 0.92346027 0.78422136
 0.85729914 0.53975311 0.31345636 0.83314588 0.91183291 0.96342691
 0.79343275 0.9790145  0.21633802 0.68830934 0.19049322 0.2485557 ]
0.6037939870138306


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [33]:
size= int(input("enter size"))
matrix = np.zeros((size,size))
matrix[0,:]  = 1
matrix[-1,:] = 1
matrix[:,0]  = 1
matrix[:,-1] = 1


print(matrix)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [36]:
original_array = np.array([[1, 2], [3, 4]])
border_size=1


rows, cols = original_array.shape
new_matrix = np.zeros((rows + 2 * border_size, cols + 2 * border_size))
new_matrix[border_size:border_size+rows, border_size:border_size+cols] = original_array

    


print(new_matrix)

[[0. 0. 0. 0.]
 [0. 1. 2. 0.]
 [0. 3. 4. 0.]
 [0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [35]:
0 * np.nan            # np.nan
np.nan == np.nan       # False
np.inf > np.nan        # False
np.nan - np.nan        # np.nan
np.nan in set([np.nan])# True
0.3 == 3 * 0.1        # False


False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [43]:
matrix = np.zeros((5,5))

for i in range(1,5):
    matrix[i ,i-1]=i
print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [44]:
matrix = np.zeros((8, 8))
matrix[1: :2, ::2] = 1
matrix[::2, 1: :2] = 1

print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [52]:
shape = (6, 7, 8)

linear_index = 100

z = linear_index % shape[2]
y = (linear_index // shape[2]) % shape[1]
x = (linear_index // (shape[1] * shape[2]))

print(x,y,z)


1 5 4


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [56]:
matrix = np.array([[1, 0], [0, 1]])

checkerboard = np.tile(matrix, (4, 4))

print(checkerboard)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [58]:
matrix = np.random.rand(5, 5)
min_val = np.min(matrix)
max_val = np.max(matrix)
Normalize_matrix = (matrix - min_val) / (max_val - min_val)

print("Original Matrix:")
print(matrix)
print("\nNormalized Matrix:")
print(Normalize_matrix)


Original Matrix:
[[0.75294966 0.78157476 0.27453726 0.95591918 0.41469555]
 [0.91758923 0.93319026 0.51047629 0.97884003 0.06972596]
 [0.53540577 0.42677653 0.39846324 0.81430918 0.27501579]
 [0.39085306 0.61259653 0.13401009 0.89173323 0.45011963]
 [0.76992323 0.00116217 0.8597852  0.33947573 0.0324159 ]]

Normalized Matrix:
[[0.76895214 0.79823081 0.27961673 0.97655582 0.42297509]
 [0.93735073 0.95330796 0.52094267 1.         0.07012922]
 [0.54644134 0.4353319  0.40637217 0.83171261 0.28010619]
 [0.39858823 0.6253945  0.13588108 0.91090439 0.45920796]
 [0.78631326 0.         0.87822694 0.34603787 0.03196731]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [3]:


RGBA_dtype = np.dtype([('r', np.uint8),('g', np.uint8),('b', np.uint8),('a', np.uint8)])   


colors = np.array([(255, 0, 0,10),(0, 255, 0, 10),(0, 0, 255, 10)], dtype=RGBA_dtype)

for i in colors:
    
    print(i,np.dtype(i))

(255, 0, 0, 10) [('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]
(0, 255, 0, 10) [('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]
(0, 0, 255, 10) [('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [4]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12],
    [13, 14, 15]])

B = np.array([
    [1, 2],
    [3, 4],
    [5, 6]])

C = np.dot(A, B) 

print("Matrix A (5x3):")
print(A)
print("\nMatrix B (3x2):")
print(B)
print("\nMatrix C (5x2) = A . B:")
print(C)

Matrix A (5x3):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]

Matrix B (3x2):
[[1 2]
 [3 4]
 [5 6]]

Matrix C (5x2) = A . B:
[[ 22  28]
 [ 49  64]
 [ 76 100]
 [103 136]
 [130 172]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [6]:
array = np.array([1,2,3,4,5,6,7,8,9])

array[(array >= 3) & (array <= 8)] *= -1

print(array)

[ 1  2 -3 -4 -5 -6 -7 -8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [7]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [21]:
Z=np.array([1,2,3,4,5])
try:
  Z**Z

except Exception as e:
        print(f"An unexpected error occurred 1: {e}")


try:
  2 << Z >> 2

except Exception as e:
        print(f"An unexpected error occurred 2: {e}")
try:
  Z <- Z

except Exception as e:
        print(f"An unexpected error occurred 3: {e}") 
try:   
  1j*Z  

except Exception as e:
        print(f"An unexpected error occurred 4: {e}")
try:      
  Z/1/1

except Exception as e:
        print(f"An unexpected error occurred 5: {e}")
try:        
  Z<Z>Z

except Exception as e:
        print(f"An unexpected error occurred 6: {e}")



An unexpected error occurred 11: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [11]:
A= np.array(0) / np.array(0) 
print(A)
B= np.array(0) // np.array(0)
print(B) 
c= np.array([np.nan]).astype(int).astype(float)
print(c)

nan
0
[-2.14748365e+09]


C:\Users\ahmed\AppData\Local\Temp\ipykernel_20940\4050855472.py:1: RuntimeWarning: invalid value encountered in divide
  A= np.array(0) / np.array(0)
C:\Users\ahmed\AppData\Local\Temp\ipykernel_20940\4050855472.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  B= np.array(0) // np.array(0)
C:\Users\ahmed\AppData\Local\Temp\ipykernel_20940\4050855472.py:5: RuntimeWarning: invalid value encountered in cast
  c= np.array([np.nan]).astype(int).astype(float)


#### 29. How to round away from zero a float array ? (★☆☆)

In [19]:
arr = np.array([1.2, -1.2, 2.5, -2.5, 3.25, -3.25, 0.0])
array = np.where(arr > 0, np.ceil(arr), np.floor(arr))

print(array)

[ 2. -2.  3. -3.  4. -4.  0.]


#### 30. How to find common values between two arrays? (★☆☆)

In [20]:
array1 = np.array([1, 2, 3, 4, 5, 7])
array2 = np.array([4, 5, 6, 7, 8, 9])

common_values = np.intersect1d(array1, array2)
print(common_values)

[4 5 7]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [24]:
np.seterr(all='ignore')

array = np.array([1, 0])
result = 1 / array

print(result)

np.seterr(all='warn')

[ 1. inf]


{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [29]:
if np.sqrt(-1) == np.emath.sqrt(-1):   #false
    print(True)
else:
    print(False)


False


C:\Users\ahmed\AppData\Local\Temp\ipykernel_20940\626944686.py:1: RuntimeWarning: invalid value encountered in sqrt
  if np.sqrt(-1) == np.emath.sqrt(-1):


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [31]:
from datetime import datetime, timedelta

today = datetime.today()

yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

print("Yesterday date:", yesterday)
print("Today date:", today)
print("Tomorrow date:", tomorrow)

Yesterday date: 2024-08-23 22:58:04.357482
Today date: 2024-08-24 22:58:04.357482
Tomorrow date: 2024-08-25 22:58:04.357482


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
year = 2016
month = 7
start_date = datetime(year, month, 1)
    
if month == 12:
        end_date = datetime(year + 1, 1, 1) - timedelta(days=1)
else:
        end_date = datetime(year, month + 1, 1) - timedelta(days=1)
    
current_date = start_date
dates = []
while current_date <= end_date:
        dates.append(current_date)
        current_date += timedelta(days=1)
        print(current_date)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [38]:
A = np.array([1, 2, 3, 4])
B = np.array([5, 6, 7, 8])

sum = A + B

div = -A / 2
result = sum * div
print("Result:", result)

Result: [ -3.  -8. -15. -24.]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [50]:
array = np.random.rand(5) * 10
floor_divide = np.floor(array)

print("Original array:", array)
print("Integer part using np.floor:", floor_divide)

Original array: [7.88585006 4.98998078 8.13426889 0.24721271 1.97694459]
Integer part using np.floor: [7. 4. 8. 0. 1.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [52]:
matrix = np.arange(5) 
matrix = np.tile(matrix, (5, 1)) 
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [63]:
def integer_generator(n):
    for i in range(n):
     yield i
gen = integer_generator(10)
array = np.array(list(gen))

print( array)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [75]:
vector = np.linspace(0, 1,12)[1:-1]
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [77]:
vector = np.random.rand(10)
vector = np.sort(vector)
print(vector)

[0.04632614 0.19172456 0.28232868 0.341669   0.36888077 0.52660211
 0.53586889 0.70249599 0.87560094 0.89469601]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [86]:
array = np.array([1, 2, 3, 4, 5])

total = np.add.reduce(array)

print(total)

15


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [93]:
array1 = np.random.rand(5)
array2 = np.random.rand(5)

equal = np.array_equal(array1,array2)

print(equal)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [95]:
array = np.array([1, 2, 3, 4, 5])

array.setflags(write=False)

print( array)

try:
    array[0] = 10
except ValueError as e:
    print("Error  cant write:", e)

[1 2 3 4 5]
Error  cant write: assignment destination is read-only


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [96]:
matrix = np.array([
    [1, 2],
    [3, 4],
    [-1, -1],
    [0, 5],
    [-3, 3],
    [2, -2],
    [4, 0],
    [-2, -3],
    [5, 5],
    [-4, 1]
])

r = np.sqrt(np.sum(matrix**2, axis=1))

theta = np.arctan2(matrix[:, 1], matrix[:, 0])

polar_matrix = np.vstack((r, theta)).T

print("Polar Coordinates Matrix:")
print(polar_matrix)

Polar Coordinates Matrix:
[[ 2.23606798  1.10714872]
 [ 5.          0.92729522]
 [ 1.41421356 -2.35619449]
 [ 5.          1.57079633]
 [ 4.24264069  2.35619449]
 [ 2.82842712 -0.78539816]
 [ 4.          0.        ]
 [ 3.60555128 -2.15879893]
 [ 7.07106781  0.78539816]
 [ 4.12310563  2.89661399]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [113]:
vector = np.random.rand(10)

max_index = np.argmax(vector)

vector[max_index] = 0

print(vector)

[0.5126598  0.86078202 0.41759526 0.01142268 0.33545095 0.37803542
 0.         0.11627167 0.72335851 0.41811798]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [126]:

num_points = int(input("enter the num of points"))

x = np.linspace(0, 1, num_points)
y = np.linspace(0, 1, num_points)

X, Y = np.meshgrid(x, y)

x_flat = X.flatten()
y_flat = Y.flatten()

dtype = [('x', float), ('y', float)]
structured_array = np.zeros(x_flat.shape[0],dtype=dtype)
structured_array['x'] = x_flat
structured_array['y'] = y_flat

# Print the structured array
print("Structured Array:")
print(structured_array)


Structured Array:
[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )
 (0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)
 (0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )
 (0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)
 (0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [127]:
# !!!!!!!!!!!!!! imp
def construct_cauchy_matrix(X, Y):
    X = np.asarray(X)
    Y = np.asarray(Y)

    C = np.zeros((len(X), len(Y)))

    for i in range(len(X)):
        for j in range(len(Y)):
            if X[i] == Y[j]:
                C[i, j] = np.inf  
            else:
                C[i, j] = 1 / (X[i] - Y[j])

    return C

X = np.array([1, 2, 3])
Y = np.array([4, 5])

C = construct_cauchy_matrix(X, Y)

print("Cauchy Matrix:")
print(C)

Cauchy Matrix:
[[-0.33333333 -0.25      ]
 [-0.5        -0.33333333]
 [-1.         -0.5       ]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [130]:

def print_numpy_type_ranges():
    int_types = [np.int8, np.int16, np.int32, np.int64]
    uint_types = [np.uint8, np.uint16, np.uint32, np.uint64]
    float_types = [np.float16, np.float32, np.float64]

    print("Integer Types:")
    for dtype in int_types:
        info = np.iinfo(dtype)
        print(f"{dtype.__name__.ljust(10)}: min={info.min}, max={info.max}")


    print("\nUnsigned Integer Types:")
    for dtype in uint_types:
        info = np.iinfo(dtype)
        print(f"{dtype.__name__.ljust(10)}: min={info.min}, max={info.max}")


    print("\nFloating-Point Types:")
    for dtype in float_types:
        info = np.finfo(dtype)
        print(f"{dtype.__name__.ljust(10)}: min={info.min}, max={info.max}")
        
print_numpy_type_ranges()


Integer Types:
int8      : min=-128, max=127
int16     : min=-32768, max=32767
int32     : min=-2147483648, max=2147483647
int64     : min=-9223372036854775808, max=9223372036854775807

Unsigned Integer Types:
uint8     : min=0, max=255
uint16    : min=0, max=65535
uint32    : min=0, max=4294967295
uint64    : min=0, max=18446744073709551615

Floating-Point Types:
float16   : min=-65504.0, max=65504.0
float32   : min=-3.4028234663852886e+38, max=3.4028234663852886e+38
float64   : min=-1.7976931348623157e+308, max=1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [136]:
import numpy as np

dtype = [('int', np.int32), ('float', np.float64), ('str', 'U10'), ('bool', np.bool_)]
structured_array = np.array([
    (1, 0.0, '', False),
    (2, 0.0, '', False),
    (3, 0.0, '', False),
    (4, 0.0, '', False),
    (5, 0.0, '', False),
    (0, 0.0, 'ahmed', False),
    (0, 0.0, '', True),
    (0, 0.0, '', False),
    (0, 2.5, '', False),
    (0, 3.25, '', False)
], dtype=dtype)

]print("Structured Array:")
print(structured_array)


Structured Array:
[(1, 0.  , '', False) (2, 0.  , '', False) (3, 0.  , '', False)
 (4, 0.  , '', False) (5, 0.  , '', False) (0, 0.  , 'ahmed', False)
 (0, 0.  , '',  True) (0, 0.  , '', False) (0, 2.5 , '', False)
 (0, 3.25, '', False)]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [24]:
vector = np.array([1, 3, 8, 10, 15, 20])
target = int(input("enter target"))

idx = (np.abs(vector - target)).argmin()


print(f"The closest value to {target} is {vector[idx]}")

The closest value to 18 is 20


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [46]:

dtype = np.dtype([
    ('position', [('x', 'f4'), ('y', 'f4')]),
    ('color', [('r', 'u1'), ('g', 'u1'), ('b', 'u1')])
])

data = np.array([
    ((10, 20), (255, 0, 0)),  
    ((30.5, 40.5), (0, 255, 0)),  
    ((50, 60), (0, 0, 255))   
], dtype=dtype)


print("Positions:", data['position'])
print("Colors:", data['color'])
print("#"*50)
print("First position:", data['position'][0])
print("First color:", data['color'][0])
print("#"*50)
print("X coordinate of the first position:", data['position']['x'][0])
print("Y coordinate of the first position:", data['position']['y'][0])
print("Red component of the first color:", data['color']['r'][0])
print("#"*50)
print("X coordinate of the second position:", data['position']['x'][1])
print("Y coordinate of the second position:", data['position']['y'][1])
print("Green component of the second color:", data['color']['g'][1])
print("#"*50)
print("X coordinate of the third position:", data['position']['x'][2])
print("Y coordinate of the third position:", data['position']['y'][2])
print("Blue component of the third color:", data['color']['b'][2])


Positions: [(10. , 20. ) (30.5, 40.5) (50. , 60. )]
Colors: [(255,   0,   0) (  0, 255,   0) (  0,   0, 255)]
##################################################
First position: (10., 20.)
First color: (255, 0, 0)
##################################################
X coordinate of the first position: 10.0
Y coordinate of the first position: 20.0
Red component of the first color: 255
##################################################
X coordinate of the second position: 30.5
Y coordinate of the second position: 40.5
Green component of the second color: 255
##################################################
X coordinate of the third position: 50.0
Y coordinate of the third position: 60.0
Blue component of the third color: 255


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [53]:

points = np.random.rand(100, 2)

distances = np.linalg.norm(points[:, np.newaxis, :] - points[np.newaxis, :, :], axis=-1)

print(f"Distance between point 0 and point 1: {distances[0, 1]}")


Distance between point 0 and point 1: 0.5426433238197389


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [56]:
float_array = np.array([1.12, 2.9, 3.75, 4.4], dtype=np.float32)

float_array = float_array.astype(np.int32)



print(float_array)

[1 2 3 4]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [59]:


data = np.genfromtxt('data.txt', delimiter=',', dtype=float)

# should create file
print(data)


[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [60]:
array = np.array([10, 20, 30, 40, 50])

for index in np.arange(len(array)):
    print(index, array[index])

0 10
1 20
2 30
3 40
4 50


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [67]:
import numpy as np
import matplotlib.pyplot as plt

def generate_gaussian_2d(size, mean=(0, 0), std_dev=(1, 1)):
    """
    Generate a 2D Gaussian-like array.

    Parameters:
    - size: Tuple indicating the dimensions of the output array (height, width).
    - mean: Tuple indicating the mean values (mu_x, mu_y).
    - std_dev: Tuple indicating the standard deviations (sigma_x, sigma_y).

    Returns:
    - A 2D NumPy array with Gaussian-like values.
    """
    height, width = size
    mu_x, mu_y = mean
    sigma_x, sigma_y = std_dev

    x = np.linspace(0, width-1, width)
    y = np.linspace(0, height-1, height)
    x, y = np.meshgrid(x, y)

    # Compute the Gaussian function
    gaussian = (1 / (2 * np.pi * sigma_x * sigma_y)) * \
               np.exp(- ((x - mu_x) ** 2 / (2 * sigma_x ** 2) + (y - mu_y) ** 2 / (2 * sigma_y ** 2)))

    return gaussian

# Example usage
size = (100, 100)  # Define the size of the array
mean = (50, 50)    # Define the mean (center of the Gaussian)
std_dev = (15, 15) # Define the standard deviation

gaussian_array = generate_gaussian_2d(size, mean, std_dev)

# Optionally, visualize the Gaussian-like array
plt.imshow(gaussian_array, cmap='viridis')
plt.colorbar()
plt.title('2D Gaussian-like Array')
plt.show()


AttributeError: module 'matplotlib' has no attribute 'rcParams'

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [91]:
import numpy as np

row   = int(input("enter array row size"))
col   = int(input("enter array col size"))
value = int(input("enter array element"))
p     = int(input("enter array number of elemnt"))          
array = np.zeros((row, col), dtype=int)
    

flat_indices = np.random.choice(row * col, p, replace=False)
row_indices, col_indices = np.unravel_index(flat_indices, (row, col))
array[row_indices, col_indices] = value

 



print(array)


[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 2 0 0 2]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [92]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row_means = matrix.mean(axis=1, keepdims=True)

result = matrix - row_means

print("Original matrix:\n", matrix)
print("Row means:\n", row_means)
print("Matrix after subtracting row means:\n", result)


Original matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Row means:
 [[2.]
 [5.]
 [8.]]
Matrix after subtracting row means:
 [[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


#### 59. How to sort an array by the nth column? (★★☆)

In [98]:
import numpy as np

array = np.array([[1, 5, 3],
                  [4, 2, 6],
                  [7, 8, 9]])

n =  int(input("enter array n col size "))

sorted_array = array[array[:, n].argsort()]

print("Original array:\n", array)
print(f"Array sorted by column {n}:\n", sorted_array)


Original array:
 [[1 5 3]
 [4 2 6]
 [7 8 9]]
Array sorted by column 1:
 [[4 2 6]
 [1 5 3]
 [7 8 9]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [99]:

matrix = np.array([[0, 1, 2],
                  [0, 0, 0],
                  [0, 3, 4]])

column_sums = matrix.sum(axis=0)

null_columns = (column_sums == 0)

has_null_columns = np.any(null_columns)

print("Column sums:", column_sums)
print("Null columns:", null_columns)
print("has null columns:", has_null_columns)

Column sums: [0 4 6]
Null columns: [ True False False]
Array has null columns: True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [4]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)



0.5326781648141933


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [23]:
import numpy as np

array1 = np.array([[1, 2, 3]])  
array2 = np.array([[4], [5], [6]]) 

result = np.empty((3, 3))

for i in range(array2.shape[0]):  
    for j in range(array1.shape[1]): 
        result[i, j] = array1[0, j] + array2[i, 0]

print(result)


[[5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]


#### 63. Create an array class that has a name attribute (★★☆)

In [24]:

class NamedArray(np.ndarray):
    def __new__(cls, input_array, name="Unnamed Array"):
        obj = np.asarray(input_array).view(cls)
        obj.name = name
        return obj
    
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "Unnamed Array")
    
    def __repr__(self):
        return f"{self.name}:\n{super().__repr__()}"

arr = NamedArray(np.array([1, 2, 3, 4, 5]), name="My Array")
print(arr)
print("Name:", arr.name)


[1 2 3 4 5]
Name: My Array


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [25]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[1. 2. 3. 1. 2. 2. 4. 7. 5. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [ ]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)


#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))
#Slow version

np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

#### 72. How to swap two rows of an array? (★★★)

In [ ]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [ ]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [30]:
Z = np.random.randint(0,2,100)
print ('original: ')
print (Z)
print('Negating a boolean: ')
print(np.logical_not(Z, out=Z))


Z = np.random.uniform(-1.0,1.0,10)
print ('original: ')
print (Z)
print ('Change the sign of float inplace: ')
print(np.negative(Z, out=Z))

original: 
[0 1 1 1 0 0 0 0 0 1 0 1 0 0 1 1 1 0 1 0 1 0 0 1 1 1 0 0 0 1 0 0 1 0 0 0 0
 1 1 0 0 1 1 0 0 1 1 1 0 0 0 1 0 0 0 1 0 1 1 0 1 0 1 1 1 1 1 1 0 1 1 0 0 1
 1 1 0 0 0 1 1 1 0 0 0 0 1 0 1 0 0 1 0 0 0 0 1 1 1 0]
Negating a boolean: 
[1 0 0 0 1 1 1 1 1 0 1 0 1 1 0 0 0 1 0 1 0 1 1 0 0 0 1 1 1 0 1 1 0 1 1 1 1
 0 0 1 1 0 0 1 1 0 0 0 1 1 1 0 1 1 1 0 1 0 0 1 0 1 0 0 0 0 0 0 1 0 0 1 1 0
 0 0 1 1 1 0 0 0 1 1 1 1 0 1 0 1 1 0 1 1 1 1 0 0 0 1]
original: 
[-0.7520317  -0.26616507 -0.29806366 -0.59266791  0.42008945  0.46928203
 -0.04451188  0.22005598 -0.51928589 -0.29542311]
Change the sign of float inplace: 
[ 0.7520317   0.26616507  0.29806366  0.59266791 -0.42008945 -0.46928203
  0.04451188 -0.22005598  0.51928589  0.29542311]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [29]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[12.99120343  3.33432003 18.40289168  6.13619308 14.14873193  5.50260088
  0.56592037 10.38492079  4.10506082  4.4840249 ]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [32]:
P0 = np.random.uniform(-10, 10, (5,2))
P1 = np.random.uniform(-10,10,(5,2))
p = np.random.uniform(-10, 10, (5,2))
print (np.array([distance(P0,P1,p_i) for p_i in p]))


[[7.64457049e+00 5.22247865e+00 8.70737514e-01 7.70996829e+00
  4.75111400e+00]
 [1.07172461e+00 2.05297748e+00 4.58652291e+00 1.34095864e+00
  1.22158297e+01]
 [1.21514942e-02 4.00986428e+00 8.46756715e+00 2.44219330e+00
  1.46059043e+01]
 [6.16893125e+00 3.70417593e+00 8.60603679e-02 6.68465848e+00
  6.25280474e+00]
 [6.83864457e+00 3.64795940e+00 2.41076480e+00 4.52980958e+00
  6.69933365e+00]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [34]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [35]:
Z = np.arange(1,15,dtype=int)

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)
R = rolling(Z, 4)
print ('original: ')
print (Z)
print ('after strides: ')
print(R)

original: 
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
after strides: 
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [36]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) 
rank = np.sum(S > 1e-10)
print (rank)

10


#### 83. How to find the most frequent value in an array?

In [41]:
Z = np.random.randint(0,10,50)
print (Z)
print('rank:', np.bincount(Z).argmax())

[1 8 3 2 3 7 8 4 8 8 3 5 6 5 9 6 4 2 3 9 6 7 3 7 9 0 8 0 4 4 4 1 6 6 9 8 7
 0 2 0 8 9 1 3 2 5 2 4 8 2]
rank: 8


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [ ]:
Z = np.random.randint(0,5,(6,6))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = np.lib.stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [49]:
class Symetric(np.ndarray):
    def __setitem__(self, i,j, value):
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

TypeError: Symetric.__setitem__() missing 1 required positional argument: 'value'

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [50]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)


[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [51]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print ('input array')
print (Z)
print ('block sum')
print (S)

input array
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
block sum
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [64]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z

SyntaxError: incomplete input (3079115480.py, line 14)

#### 89. How to get the n largest values of an array (★★★)

In [59]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])

print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9996 9997 9998 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [58]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [65]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [71]:
x = np.random.rand(5e7)

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

TypeError: 'float' object cannot be interpreted as an integer

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [72]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[0 1 3 4 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [73]:
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[1 4 3]
 [2 4 3]
 [3 0 3]
 [3 4 4]
 [4 3 1]
 [1 3 2]
 [3 4 4]
 [4 0 2]
 [0 3 4]
 [3 2 1]]
[[1 4 3]
 [2 4 3]
 [3 0 3]
 [3 4 4]
 [4 3 1]
 [1 3 2]
 [3 4 4]
 [4 0 2]
 [0 3 4]
 [3 2 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [75]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])


I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [76]:

Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [ ]:

A= np.arange(3)
B =  np.arange(12).reshape(3,4)
print (A)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [80]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)      
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [81]:

def select_multinomial_rows(X, n):
    integer_rows = np.all(np.equal(np.mod(X, 1), 0), axis=1)
    
    sum_to_n = np.sum(X, axis=1) == n
    
    valid_rows = np.logical_and(integer_rows, sum_to_n)
    
    return X[valid_rows]

X = np.array([[1.0, 2.0, 3.0],
              [2, 2, 1],
              [3, 0.5, 2.5],
              [3, 3, 0]])

n = 6
result = select_multinomial_rows(X, n)
print(result)


[[1. 2. 3.]
 [3. 3. 0.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [85]:
import numpy as np

def bootstrap_confidence_interval(X, num_samples=1000, confidence_level=95):
    bootstrapped_means = np.empty(num_samples)

    for i in range(num_samples):
        bootstrap_sample = np.random.choice(X, size=len(X), replace=True)
        bootstrapped_means[i] = np.mean(bootstrap_sample)
    
    lower_percentile = (100 - confidence_level) / 2
    upper_percentile = 100 - lower_percentile
    confidence_interval = np.percentile(bootstrapped_means, [lower_percentile, upper_percentile])
    
    return confidence_interval

X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
confidence_interval = bootstrap_confidence_interval(X)
print("95% Confidence Interval for the mean:", confidence_interval)


95% Confidence Interval for the mean: [3.6 7.1]
